# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cross-platform-todo-list' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cross-platform-todo-list
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
end
